/**
 * 2016/9/23 16:23:21 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.topupwithdrawal.dao;

import com.lolluckyman.business.topupwithdrawal.entity.TopUpWithdrawal;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 充值提现记录 Ibatis Dao 接口
 * Created by lenovo on 2016/09/23.
 */
public interface ITopUpWithdrawalDao extends IIbatisDataDAO<TopUpWithdrawal, String> {

}
