/**
 * 2016/9/23 16:23:21 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.topupwithdrawal.dao;

import com.lolluckyman.business.topupwithdrawal.entity.TopUpWithdrawal;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 充值提现记录 Ibatis Dao 实现
 * Created by lenovo on 2016/09/23.
 */
@Repository
public class TopUpWithdrawalDao extends IbatisDataDAOImpl<TopUpWithdrawal, String> implements ITopUpWithdrawalDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="topUpWithdrawalDao" class="com.lolluckyman.business.topupwithdrawal.entity.daos.TopUpWithdrawalDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public TopUpWithdrawalDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.topupwithdrawal.dao.ITopUpWithdrawalDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
