/**
 * 2016/9/11 11:55:03 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.serianum.entity;

/**
 * 主键序列号信息
 * Created by lenovo on 2016/09/11.
 */
public class SeriaNum implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -3409682667539307008L;

    // 序列号发送器的键 [主键]
    private String keyName;
    // 当前已产生的最大序列号
    private int keyValue;

    /** 
     * 获取序列号发送器的键 [主键]
     * 
     * @return 序列号发送器的键
     */
    public String getKeyName() {
        return keyName;
    }

    /** 
     * 设置序列号发送器的键 [主键]
     * 
     * @param keyName 序列号发送器的键
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }

    /** 
     * 获取当前已产生的最大序列号
     * 
     * @return 当前已产生的最大序列号
     */
    public int getKeyValue() {
        return keyValue;
    }

    /** 
     * 设置当前已产生的最大序列号
     * 
     * @param keyValue 当前已产生的最大序列号
     */
    public void setKeyValue(int keyValue) {
        this.keyValue = keyValue;
    }

}
