/**
 * 2016/9/22 18:57:00 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.competition.dao;

import com.lolluckyman.business.competition.entity.Competition;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 比赛信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/22.
 */
public interface ICompetitionDao extends IIbatisDataDAO<Competition, String> {

}
