/**
 * 2016/9/11 11:55:03 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.serianum.dao;


import com.lolluckyman.business.serianum.entity.SeriaNum;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 主键序列号信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/11.
 */
public interface ISeriaNumDao extends IIbatisDataDAO<SeriaNum, String> {

}
