/**
 * 2016/9/11 11:55:03 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.serianum.dao;

import com.lolluckyman.business.serianum.entity.SeriaNum;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 主键序列号信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/11.
 */
@Repository
public class SeriaNumDao extends IbatisDataDAOImpl<SeriaNum, String> implements ISeriaNumDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="seriaNumDao" class="com.dyb.platforms.fixfunds.services.business.serianum.entity.daos.SeriaNumDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public SeriaNumDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.serianum.dao.ISeriaNumDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
