/**
 * 2016/9/11 16:06:38 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.systemparams.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 系统参数信息
 * Created by lenovo on 2016/09/11.
 */
public class SystemParams implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -3332796233395485184L;

    // 系统参数Code [主键]
    private String systemParamsCode;
    // 系统参数Key
    private String systemParamsKey;
    // 系统参数Value
    private String systemParamsValue;
    // 描述
    private String description;
    // 创建时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * 获取系统参数Code [主键]
     *
     * @return 系统参数Code
     */
    public String getSystemParamsCode() {
        return systemParamsCode;
    }

    /**
     * 设置系统参数Code [主键]
     *
     * @param systemParamsCode 系统参数Code
     */
    public void setSystemParamsCode(String systemParamsCode) {
        this.systemParamsCode = systemParamsCode;
    }

    /**
     * 获取系统参数Key
     *
     * @return 系统参数Key
     */
    public String getSystemParamsKey() {
        return systemParamsKey;
    }

    /**
     * 设置系统参数Key
     *
     * @param systemParamsKey 系统参数Key
     */
    public void setSystemParamsKey(String systemParamsKey) {
        this.systemParamsKey = systemParamsKey;
    }

    /**
     * 获取系统参数Value
     *
     * @return 系统参数Value
     */
    public String getSystemParamsValue() {
        return systemParamsValue;
    }

    /**
     * 设置系统参数Value
     *
     * @param systemParamsValue 系统参数Value
     */
    public void setSystemParamsValue(String systemParamsValue) {
        this.systemParamsValue = systemParamsValue;
    }

    /**
     * 获取描述
     *
     * @return 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置描述
     *
     * @param description 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 获取创建时间
     *
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
