/**
 * 2016/9/23 16:23:20 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.topupwithdrawal.entity;

import java.util.Date;

/**
 * 充值提现记录
 * Created by lenovo on 2016/09/23.
 */
public class TopUpWithdrawal implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -7802323502396384256L;

    // 充值提现code [主键]
    private String code;
    // 申请金额
    private Double applyMoney;
    // 申请人code
    private String applyAccountCode;
    // 实际到账金额
    private Double money;
    // 申请时间
    private Date applyTime;
    // 业务类型（充值、提现）
    private String businessType;
    // 交易类型（微信、支付宝）
    private String tradeType;
    // 交易账号
    private String tradeNumber;
    // 处理状态
    private String disposalStatus;
    // 处理时间
    private Date disposalTime;

    /** 
     * 获取充值提现code [主键]
     * 
     * @return 充值提现code
     */
    public String getCode() {
        return code;
    }

    /** 
     * 设置充值提现code [主键]
     * 
     * @param code 充值提现code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** 
     * 获取申请金额
     * 
     * @return 申请金额
     */
    public Double getApplyMoney() {
        return applyMoney;
    }

    /** 
     * 设置申请金额
     * 
     * @param applyMoney 申请金额
     */
    public void setApplyMoney(Double applyMoney) {
        this.applyMoney = applyMoney;
    }

    /** 
     * 获取申请人code
     * 
     * @return 申请人code
     */
    public String getApplyAccountCode() {
        return applyAccountCode;
    }

    /** 
     * 设置申请人code
     * 
     * @param applyAccountCode 申请人code
     */
    public void setApplyAccountCode(String applyAccountCode) {
        this.applyAccountCode = applyAccountCode;
    }

    /** 
     * 获取实际到账金额
     * 
     * @return 实际到账金额
     */
    public Double getMoney() {
        return money;
    }

    /** 
     * 设置实际到账金额
     * 
     * @param money 实际到账金额
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /** 
     * 获取申请时间
     * 
     * @return 申请时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /** 
     * 设置申请时间
     * 
     * @param applyTime 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /** 
     * 获取业务类型（充值、提现）
     * 
     * @return 业务类型（充值、提现）
     */
    public String getBusinessType() {
        return businessType;
    }

    /** 
     * 设置业务类型（充值、提现）
     * 
     * @param businessType 业务类型（充值、提现）
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /** 
     * 获取交易类型（微信、支付宝）
     * 
     * @return 交易类型（微信、支付宝）
     */
    public String getTradeType() {
        return tradeType;
    }

    /** 
     * 设置交易类型（微信、支付宝）
     * 
     * @param tradeType 交易类型（微信、支付宝）
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /** 
     * 获取交易账号
     * 
     * @return 交易账号
     */
    public String getTradeNumber() {
        return tradeNumber;
    }

    /** 
     * 设置交易账号
     * 
     * @param tradeNumber 交易账号
     */
    public void setTradeNumber(String tradeNumber) {
        this.tradeNumber = tradeNumber;
    }

    /** 
     * 获取处理状态
     * 
     * @return 处理状态
     */
    public String getDisposalStatus() {
        return disposalStatus;
    }

    /** 
     * 设置处理状态
     * 
     * @param disposalStatus 处理状态
     */
    public void setDisposalStatus(String disposalStatus) {
        this.disposalStatus = disposalStatus;
    }

    /** 
     * 获取处理时间
     * 
     * @return 处理时间
     */
    public Date getDisposalTime() {
        return disposalTime;
    }

    /** 
     * 设置处理时间
     * 
     * @param disposalTime 处理时间
     */
    public void setDisposalTime(Date disposalTime) {
        this.disposalTime = disposalTime;
    }

}
