/**
 * 2016/9/22 15:44:27 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.playrecord.dao;

import com.lolluckyman.business.playrecord.entity.PlayRecord;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 联盟玩法 Ibatis Dao 接口
 * Created by lenovo on 2016/09/22.
 */
public interface IPlayRecordDao extends IIbatisDataDAO<PlayRecord, String> {

}
