/**
 * 2016/9/22 19:05:55 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.restrain.dao;

import com.lolluckyman.business.restrain.entity.Restrain;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 比赛信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/22.
 */
public interface IRestrainDao extends IIbatisDataDAO<Restrain, String> {

}
