/**
 * 2016/9/22 19:05:55 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.restrain.dao;

import com.lolluckyman.business.restrain.entity.Restrain;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 比赛信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/22.
 */
@Repository
public class RestrainDao extends IbatisDataDAOImpl<Restrain, String> implements IRestrainDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="restrainDao" class="com.lolluckyman.business.restrain.entity.daos.RestrainDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public RestrainDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.restrain.dao.IRestrainDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
