/**
 * 2016/9/21 23:03:35 魏源 created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.accountassets.dao;

import java.util.*;
import java.math.*;

import com.lolluckyman.business.accountassets.entity.AccountAssets;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 账户资产信息 Ibatis Dao 接口
 * Created by 魏源 on 2016/09/21.
 */
public interface IAccountAssetsDao extends IIbatisDataDAO<AccountAssets, String> {

}
