/**
 * 2016/9/24 22:29:16 魏源 created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.account.entity;

import com.lolluckyman.business.account.entity.em.*;

import java.util.*;
import java.math.*;

/**
 * 账户信息
 * Created by lenovo on 2016/09/24.
 */
public class Account implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -6189979625022960640L;

    // 账户code [主键]
    private String code;
    // 会员账号
    private String loginAccount;
    // 会员密码
    private String password;
    // 真实姓名
    private String realName;
    // 联系电话
    private String phone;
    // 邮箱地址
    private String email;
    // QQ
    private String qq;
    // 密码问题
    private Problem passwordProblem;
    // 密码答案
    private String passwordAnswer;
    // 取款密码
    private String withdrawalsPassword;
    // 账户状态
    private AccountStatus accountStatus;
    // 账户描述
    private String description;
    // 添加时间
    private Date createTime;
    // 充值状态
    private WithdrawalsStatus withdrawalsStatus;
    // 提现状态
    private RechargeStatus rechargeStatus;
    // 兑换奖品状态
    private ExchangePrizeStatus exchangePrizeStatus;
    // 投注状态
    private BettingStatus bettingStatus;

    /**
     * 获取账户code [主键]
     *
     * @return 账户code
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置账户code [主键]
     *
     * @param code 账户code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 获取会员账号
     *
     * @return 会员账号
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * 设置会员账号
     *
     * @param loginAccount 会员账号
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    /**
     * 获取会员密码
     *
     * @return 会员密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * 设置会员密码
     *
     * @param password 会员密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取真实姓名
     *
     * @return 真实姓名
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 设置真实姓名
     *
     * @param realName 真实姓名
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * 获取联系电话
     *
     * @return 联系电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置联系电话
     *
     * @param phone 联系电话
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 获取邮箱地址
     *
     * @return 邮箱地址
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置邮箱地址
     *
     * @param email 邮箱地址
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 获取QQ
     *
     * @return QQ
     */
    public String getQq() {
        return qq;
    }

    /**
     * 设置QQ
     *
     * @param qq QQ
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * 获取密码问题
     *
     * @return 密码问题
     */
    public Problem getPasswordProblem() {
        return passwordProblem;
    }

    /**
     * 设置密码问题
     *
     * @param passwordProblem 密码问题
     */
    public void setPasswordProblem(Problem passwordProblem) {
        this.passwordProblem = passwordProblem;
    }

    /**
     * 获取密码答案
     *
     * @return 密码答案
     */
    public String getPasswordAnswer() {
        return passwordAnswer;
    }

    /**
     * 设置密码答案
     *
     * @param passwordAnswer 密码答案
     */
    public void setPasswordAnswer(String passwordAnswer) {
        this.passwordAnswer = passwordAnswer;
    }

    /**
     * 获取取款密码
     *
     * @return 取款密码
     */
    public String getWithdrawalsPassword() {
        return withdrawalsPassword;
    }

    /**
     * 设置取款密码
     *
     * @param withdrawalsPassword 取款密码
     */
    public void setWithdrawalsPassword(String withdrawalsPassword) {
        this.withdrawalsPassword = withdrawalsPassword;
    }

    /**
     * 获取账户状态
     *
     * @return 账户状态
     */
    public AccountStatus getAccountStatus() {
        return accountStatus;
    }

    /**
     * 设置账户状态
     *
     * @param accountStatus 账户状态
     */
    public void setAccountStatus(AccountStatus accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * 获取账户描述
     *
     * @return 账户描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置账户描述
     *
     * @param description 账户描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 获取添加时间
     *
     * @return 添加时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置添加时间
     *
     * @param createTime 添加时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取充值状态
     *
     * @return 充值状态
     */
    public WithdrawalsStatus getWithdrawalsStatus() {
        return withdrawalsStatus;
    }

    /**
     * 设置充值状态
     *
     * @param withdrawalsStatus 充值状态
     */
    public void setWithdrawalsStatus(WithdrawalsStatus withdrawalsStatus) {
        this.withdrawalsStatus = withdrawalsStatus;
    }

    /**
     * 获取提现状态
     *
     * @return 提现状态
     */
    public RechargeStatus getRechargeStatus() {
        return rechargeStatus;
    }

    /**
     * 设置提现状态
     *
     * @param rechargeStatus 提现状态
     */
    public void setRechargeStatus(RechargeStatus rechargeStatus) {
        this.rechargeStatus = rechargeStatus;
    }

    /**
     * 获取兑换奖品状态
     *
     * @return 兑换奖品状态
     */
    public ExchangePrizeStatus getExchangePrizeStatus() {
        return exchangePrizeStatus;
    }

    /**
     * 设置兑换奖品状态
     *
     * @param exchangePrizeStatus 兑换奖品状态
     */
    public void setExchangePrizeStatus(ExchangePrizeStatus exchangePrizeStatus) {
        this.exchangePrizeStatus = exchangePrizeStatus;
    }

    /**
     * 获取投注状态
     *
     * @return 投注状态
     */
    public BettingStatus getBettingStatus() {
        return bettingStatus;
    }

    /**
     * 设置投注状态
     *
     * @param bettingStatus 投注状态
     */
    public void setBettingStatus(BettingStatus bettingStatus) {
        this.bettingStatus = bettingStatus;
    }

}
