/**
 * 2016/9/23 16:25:27 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.exchangeprize.dao;

import com.lolluckyman.business.exchangeprize.entity.ExchangePrize;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 奖品兑换信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/23.
 */
@Repository
public class ExchangePrizeDao extends IbatisDataDAOImpl<ExchangePrize, String> implements IExchangePrizeDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="exchangePrizeDao" class="com.lolluckyman.business.exchangeprize.entity.daos.ExchangePrizeDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public ExchangePrizeDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.exchangeprize.dao.IExchangePrizeDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
