/**
 * 2016/9/23 16:25:27 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.exchangeprize.dao;

import com.lolluckyman.business.exchangeprize.entity.ExchangePrize;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 奖品兑换信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/23.
 */
public interface IExchangePrizeDao extends IIbatisDataDAO<ExchangePrize, String> {

}
