/**
 * 2016/9/22 11:31:15 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.team.dao;

import com.lolluckyman.business.team.entity.Team;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 战队信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/22.
 */
public interface ITeamDao extends IIbatisDataDAO<Team, String> {

}
