/**
 * 2016/9/22 11:31:15 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.team.dao;

import com.lolluckyman.business.team.entity.Team;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 战队信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/22.
 */
@Repository
public class TeamDao extends IbatisDataDAOImpl<Team, String> implements ITeamDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="teamDao" class="com.lolluckyman.business.team.entity.daos.TeamDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public TeamDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.team.dao.ITeamDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.team.dao.ITeamDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.team.dao.ITeamDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.team.dao.ITeamDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.team.dao.ITeamDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.team.dao.ITeamDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.team.dao.ITeamDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.team.dao.ITeamDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.team.dao.ITeamDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
