/**
 * 2016/9/23 16:26:58 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.bettingrecord.dao;

import com.lolluckyman.business.bettingrecord.entity.BettingRecord;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 投注信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/23.
 */
@Repository
public class BettingRecordDao extends IbatisDataDAOImpl<BettingRecord, String> implements IBettingRecordDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="bettingRecordDao" class="com.lolluckyman.business.bettingrecord.entity.daos.BettingRecordDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public BettingRecordDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.bettingrecord.dao.IBettingRecordDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
