/**
 * 2016/9/23 16:26:58 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.bettingrecord.dao;

import com.lolluckyman.business.bettingrecord.entity.BettingRecord;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 投注信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/23.
 */
public interface IBettingRecordDao extends IIbatisDataDAO<BettingRecord, String> {

}
