/**
 * 2016/9/22 10:38:04 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.prize.dao;

import com.lolluckyman.business.prize.entity.Prize;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 奖品信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/22.
 */
public interface IPrizeDao extends IIbatisDataDAO<Prize, String> {

}
