/**
 * 2016/9/22 10:38:04 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.prize.dao;

import com.lolluckyman.business.prize.entity.Prize;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 奖品信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/22.
 */
@Repository
public class PrizeDao extends IbatisDataDAOImpl<Prize, String> implements IPrizeDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="prizeDao" class="com.lolluckyman.business.prize.entity.daos.PrizeDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public PrizeDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.prize.dao.IPrizeDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
