/**
 * 2016/9/21 21:18:56 魏源 created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.account.dao;

import java.util.*;
import java.math.*;

import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import com.lolluckyman.business.account.entity.Account;

/**
 * 账户信息 Ibatis Dao 实现
 * Created by 魏源 on 2016/09/21.
 */
@Repository
public class AccountDao extends IbatisDataDAOImpl<Account, String> implements IAccountDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="accountDao" class="com.lolluckyman.business.account.entity.daos.AccountDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public AccountDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.account.dao.IAccountDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.account.dao.IAccountDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.account.dao.IAccountDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.account.dao.IAccountDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.account.dao.IAccountDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.account.dao.IAccountDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.account.dao.IAccountDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.account.dao.IAccountDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.account.dao.IAccountDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
