/**
 * 2016/9/21 21:18:56 魏源 created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.account.dao;

import java.util.*;
import java.math.*;

import com.lolluckyman.business.account.entity.Account;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 账户信息 Ibatis Dao 接口
 * Created by 魏源 on 2016/09/21.
 */
public interface IAccountDao extends IIbatisDataDAO<Account, String> {

}
