/**
 * 2016/9/21 16:55:15 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.systemparams.dao;

import com.lolluckyman.business.systemparams.entity.SystemParams;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 系统参数配置 Ibatis Dao 接口
 * Created by lenovo on 2016/09/21.
 */
public interface ISystemParamsDao extends IIbatisDataDAO<SystemParams, String> {

}
