/**
 * 2016/9/21 16:55:15 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.systemparams.dao;

import com.lolluckyman.business.systemparams.entity.SystemParams;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 系统参数配置 Ibatis Dao 实现
 * Created by lenovo on 2016/09/21.
 */
@Repository
public class SystemParamsDao extends IbatisDataDAOImpl<SystemParams, String> implements ISystemParamsDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="systemParamsDao" class="com.lolluckyman.business.systemparams.entity.daos.SystemParamsDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public SystemParamsDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.systemparams.dao.ISystemParamsDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
