/**
 * 2016/9/22 18:57:00 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.competition.entity;

import com.lolluckyman.business.competition.entity.em.CompetitionStatus;

import java.util.Date;

/**
 * 比赛信息
 * Created by lenovo on 2016/09/22.
 */
public class Competition implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -4226818924875380224L;

    // 比赛code [主键]
    private String code;
    // 比赛名称
    private String competitionName;
    // PK战队A
    private String teamCodeA;
    // PK战队B
    private String teamCodeB;
    // 比赛开始时间
    private Date gameStartTime;
    // 比赛状态
    private CompetitionStatus competitionStatus;
    // 比赛描述
    private String description;
    // 添加时间
    private Date createTime;

    /** 
     * 获取比赛code [主键]
     * 
     * @return 比赛code
     */
    public String getCode() {
        return code;
    }

    /** 
     * 设置比赛code [主键]
     * 
     * @param code 比赛code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** 
     * 获取比赛名称
     * 
     * @return 比赛名称
     */
    public String getCompetitionName() {
        return competitionName;
    }

    /** 
     * 设置比赛名称
     * 
     * @param competitionName 比赛名称
     */
    public void setCompetitionName(String competitionName) {
        this.competitionName = competitionName;
    }

    /** 
     * 获取PK战队A
     * 
     * @return PK战队A
     */
    public String getTeamCodeA() {
        return teamCodeA;
    }

    /** 
     * 设置PK战队A
     * 
     * @param teamCodeA PK战队A
     */
    public void setTeamCodeA(String teamCodeA) {
        this.teamCodeA = teamCodeA;
    }

    /** 
     * 获取PK战队B
     * 
     * @return PK战队B
     */
    public String getTeamCodeB() {
        return teamCodeB;
    }

    /** 
     * 设置PK战队B
     * 
     * @param teamCodeB PK战队B
     */
    public void setTeamCodeB(String teamCodeB) {
        this.teamCodeB = teamCodeB;
    }

    /** 
     * 获取比赛开始时间
     * 
     * @return 比赛开始时间
     */
    public Date getGameStartTime() {
        return gameStartTime;
    }

    /** 
     * 设置比赛开始时间
     * 
     * @param gameStartTime 比赛开始时间
     */
    public void setGameStartTime(Date gameStartTime) {
        this.gameStartTime = gameStartTime;
    }

    /** 
     * 获取比赛状态
     * 
     * @return 比赛状态
     */
    public CompetitionStatus getCompetitionStatus() {
        return competitionStatus;
    }

    /** 
     * 设置比赛状态
     * 
     * @param competitionStatus 比赛状态
     */
    public void setCompetitionStatus(CompetitionStatus competitionStatus) {
        this.competitionStatus = competitionStatus;
    }

    /** 
     * 获取比赛描述
     * 
     * @return 比赛描述
     */
    public String getDescription() {
        return description;
    }

    /** 
     * 设置比赛描述
     * 
     * @param description 比赛描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** 
     * 获取添加时间
     * 
     * @return 添加时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置添加时间
     * 
     * @param createTime 添加时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
