/**
 * 2016/9/22 10:38:04 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.prize.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.lolluckyman.business.prize.entity.em.PrizeType;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 奖品信息
 * Created by lenovo on 2016/09/22.
 */
public class Prize implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -4679415027927334912L;

    // 奖品code [主键]
    private String code;
    // 奖品名称
    private String prizeName;
    // 奖品类型
    private PrizeType prizeType;
    // 奖品描述
    private String description;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 添加时间
    private Date createTime;

    /** 
     * 获取奖品code [主键]
     * 
     * @return 奖品code
     */
    public String getCode() {
        return code;
    }

    /** 
     * 设置奖品code [主键]
     * 
     * @param code 奖品code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** 
     * 获取奖品名称
     * 
     * @return 奖品名称
     */
    public String getPrizeName() {
        return prizeName;
    }

    /** 
     * 设置奖品名称
     * 
     * @param prizeName 奖品名称
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName;
    }

    /** 
     * 获取奖品类型
     * 
     * @return 奖品类型
     */
    public PrizeType getPrizeType() {
        return prizeType;
    }

    /** 
     * 设置奖品类型
     * 
     * @param prizeType 奖品类型
     */
    public void setPrizeType(PrizeType prizeType) {
        this.prizeType = prizeType;
    }

    /** 
     * 获取奖品描述
     * 
     * @return 奖品描述
     */
    public String getDescription() {
        return description;
    }

    /** 
     * 设置奖品描述
     * 
     * @param description 奖品描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** 
     * 获取添加时间
     * 
     * @return 添加时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置添加时间
     * 
     * @param createTime 添加时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
