/**
 * 2016/9/21 16:54:44 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.admin.dao;

import com.lolluckyman.business.admin.entity.Admin;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 管理员信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/21.
 */
@Repository
public class AdminDao extends IbatisDataDAOImpl<Admin, String> implements IAdminDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="adminDao" class="com.lolluckyman.business.admin.entity.daos.AdminDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public AdminDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.admin.dao.IAdminDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.admin.dao.IAdminDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.admin.dao.IAdminDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.admin.dao.IAdminDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.admin.dao.IAdminDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.admin.dao.IAdminDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.admin.dao.IAdminDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.admin.dao.IAdminDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.admin.dao.IAdminDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
