/**
 * 2016/9/21 16:54:44 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.admin.dao;

import com.lolluckyman.business.admin.entity.Admin;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 管理员信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/21.
 */
public interface IAdminDao extends IIbatisDataDAO<Admin, String> {

}
