/**
 * 2016/9/21 23:03:35 魏源 created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.accountassets.entity;

import java.util.*;
import java.math.*;

/**
 * 账户资产信息
 * Created by 魏源 on 2016/09/21.
 */
public class AccountAssets implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -2788704849215552512L;

    // 账户资产code [主键]
    private String code;
    // 可用竞猜币
    private Double quizMoney;
    // 可用抚恤金
    private Double pensionMoney;
    // 可用胜利币
    private Double victoryMoney;
    // 冻结竞猜币
    private Double freezeQuizMoney;
    // 冻结抚恤金
    private Double freezePensionMoney;
    // 冻结胜利币
    private Double freezeVictoryMoney;
    // 账户外键
    private String accountCode;

    /** 
     * 获取账户资产code [主键]
     * 
     * @return 账户资产code
     */
    public String getCode() {
        return code;
    }

    /** 
     * 设置账户资产code [主键]
     * 
     * @param code 账户资产code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** 
     * 获取可用竞猜币
     * 
     * @return 可用竞猜币
     */
    public Double getQuizMoney() {
        return quizMoney;
    }

    /** 
     * 设置可用竞猜币
     * 
     * @param quizMoney 可用竞猜币
     */
    public void setQuizMoney(Double quizMoney) {
        this.quizMoney = quizMoney;
    }

    /** 
     * 获取可用抚恤金
     * 
     * @return 可用抚恤金
     */
    public Double getPensionMoney() {
        return pensionMoney;
    }

    /** 
     * 设置可用抚恤金
     * 
     * @param pensionMoney 可用抚恤金
     */
    public void setPensionMoney(Double pensionMoney) {
        this.pensionMoney = pensionMoney;
    }

    /** 
     * 获取可用胜利币
     * 
     * @return 可用胜利币
     */
    public Double getVictoryMoney() {
        return victoryMoney;
    }

    /** 
     * 设置可用胜利币
     * 
     * @param victoryMoney 可用胜利币
     */
    public void setVictoryMoney(Double victoryMoney) {
        this.victoryMoney = victoryMoney;
    }

    /** 
     * 获取冻结竞猜币
     * 
     * @return 冻结竞猜币
     */
    public Double getFreezeQuizMoney() {
        return freezeQuizMoney;
    }

    /** 
     * 设置冻结竞猜币
     * 
     * @param freezeQuizMoney 冻结竞猜币
     */
    public void setFreezeQuizMoney(Double freezeQuizMoney) {
        this.freezeQuizMoney = freezeQuizMoney;
    }

    /** 
     * 获取冻结抚恤金
     * 
     * @return 冻结抚恤金
     */
    public Double getFreezePensionMoney() {
        return freezePensionMoney;
    }

    /** 
     * 设置冻结抚恤金
     * 
     * @param freezePensionMoney 冻结抚恤金
     */
    public void setFreezePensionMoney(Double freezePensionMoney) {
        this.freezePensionMoney = freezePensionMoney;
    }

    /** 
     * 获取冻结胜利币
     * 
     * @return 冻结胜利币
     */
    public Double getFreezeVictoryMoney() {
        return freezeVictoryMoney;
    }

    /** 
     * 设置冻结胜利币
     * 
     * @param freezeVictoryMoney 冻结胜利币
     */
    public void setFreezeVictoryMoney(Double freezeVictoryMoney) {
        this.freezeVictoryMoney = freezeVictoryMoney;
    }

    /** 
     * 获取账户外键
     * 
     * @return 账户外键
     */
    public String getAccountCode() {
        return accountCode;
    }

    /** 
     * 设置账户外键
     * 
     * @param accountCode 账户外键
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

}
