/**
 * 2016/9/21 16:54:44 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.admin.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 管理员信息
 * Created by lenovo on 2016/09/21.
 */
public class Admin implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -8861574106319609856L;

    // 管理员code [主键]
    private String code;
    // 登录名
    private String loginName;
    // 管理员密码
    private String password;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 添加时间
    private Date createTime;

    @Override
    public String toString() {
        return "Admin{" +
                "code='" + code + '\'' +
                ", loginName='" + loginName + '\'' +
                ", password='" + password + '\'' +
                ", createTime=" + createTime +
                '}';
    }

    /**
     * 获取管理员code [主键]
     * 
     * @return 管理员code
     */
    public String getCode() {
        return code;
    }

    /** 
     * 设置管理员code [主键]
     * 
     * @param code 管理员code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** 
     * 获取登录名
     * 
     * @return 登录名
     */
    public String getLoginName() {
        return loginName;
    }

    /** 
     * 设置登录名
     * 
     * @param loginName 登录名
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /** 
     * 获取管理员密码
     * 
     * @return 管理员密码
     */
    public String getPassword() {
        return password;
    }

    /** 
     * 设置管理员密码
     * 
     * @param password 管理员密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /** 
     * 获取添加时间
     * 
     * @return 添加时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置添加时间
     * 
     * @param createTime 添加时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
