/**
 * 2016/9/22 11:31:45 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.lolluckyman.business.teamplayer.dao;

import com.lolluckyman.business.teamplayer.entity.TeamPlayer;
import com.lolluckyman.utils.core.dao.IIbatisDataDAO;

/**
 * 战队队员信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/22.
 */
public interface ITeamPlayerDao extends IIbatisDataDAO<TeamPlayer, String> {

}
