/**
 * 2016/9/22 11:31:45 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.lolluckyman.business.teamplayer.dao;

import com.lolluckyman.business.teamplayer.entity.TeamPlayer;
import com.lolluckyman.utils.core.dao.IbatisBaseStatement;
import com.lolluckyman.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 战队队员信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/22.
 */
@Repository
public class TeamPlayerDao extends IbatisDataDAOImpl<TeamPlayer, String> implements ITeamPlayerDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="teamPlayerDao" class="com.lolluckyman.business.teamplayer.entity.daos.TeamPlayerDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public TeamPlayerDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.lolluckyman.business.teamplayer.dao.ITeamPlayerDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
