/**
 * 2016/9/22 11:31:15 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.lolluckyman.business.team.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 战队信息
 * Created by lenovo on 2016/09/22.
 */
public class Team implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -5026730664552529920L;

    // 战队code [主键]
    private String code;
    // 中文名字
    private String chinaName;
    // 外文名字
    private String englishName;
    // 战队教练
    private String teamTeacher;
    // 战队网站
    private String teamWeb;
    @JsonFormat(pattern = "yyyy-MM-dd", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    // 建队时间
    private Date createTeamTime;
    // 战队简介
    private String description;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 添加时间
    private Date createTime;
    //战队图片
    private String teamphone;

    /** 
     * 获取战队code [主键]
     * 
     * @return 战队code
     */
    public String getCode() {
        return code;
    }

    /** 
     * 设置战队code [主键]
     * 
     * @param code 战队code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** 
     * 获取中文名字
     * 
     * @return 中文名字
     */
    public String getChinaName() {
        return chinaName;
    }

    /** 
     * 设置中文名字
     * 
     * @param chinaName 中文名字
     */
    public void setChinaName(String chinaName) {
        this.chinaName = chinaName;
    }

    /** 
     * 获取外文名字
     * 
     * @return 外文名字
     */
    public String getEnglishName() {
        return englishName;
    }

    /** 
     * 设置外文名字
     * 
     * @param englishName 外文名字
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    /** 
     * 获取战队教练
     * 
     * @return 战队教练
     */
    public String getTeamTeacher() {
        return teamTeacher;
    }

    /** 
     * 设置战队教练
     * 
     * @param teamTeacher 战队教练
     */
    public void setTeamTeacher(String teamTeacher) {
        this.teamTeacher = teamTeacher;
    }

    /** 
     * 获取战队网站
     * 
     * @return 战队网站
     */
    public String getTeamWeb() {
        return teamWeb;
    }

    /** 
     * 设置战队网站
     * 
     * @param teamWeb 战队网站
     */
    public void setTeamWeb(String teamWeb) {
        this.teamWeb = teamWeb;
    }

    /** 
     * 获取建队时间
     * 
     * @return 建队时间
     */
    public Date getCreateTeamTime() {
        return createTeamTime;
    }

    /** 
     * 设置建队时间
     * 
     * @param createTeamTime 建队时间
     */
    public void setCreateTeamTime(Date createTeamTime) {
        this.createTeamTime = createTeamTime;
    }

    /** 
     * 获取战队简介
     * 
     * @return 战队简介
     */
    public String getDescription() {
        return description;
    }

    /** 
     * 设置战队简介
     * 
     * @param description 战队简介
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** 
     * 获取添加时间
     * 
     * @return 添加时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置添加时间
     * 
     * @param createTime 添加时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getTeamphone() {
        return teamphone;
    }

    public void setTeamphone(String teamphone) {
        this.teamphone = teamphone;
    }
}
